pull_request_rules:
    - name: automatically merge approved PRs with the ready-to-merge label
      conditions:
          - "status-success=ci/circleci: build-artifacts--testnet_postake_medium_curves"
          - "status-success=ci/circleci: build-client-sdk"
          - "status-success=ci/circleci: build-wallet"
          - "status-success=ci/circleci: compare-test-signatures"
          - "status-success=ci/circleci: lint"
          - "status-success=ci/circleci: test--fake_hash"
          - "status-success=ci/circleci: test--test_postake"
          - "status-success=ci/circleci: test--test_postake_bootstrap"
          - "status-success=ci/circleci: test--test_postake_delegation"
          - "status-success=ci/circleci: test--test_postake_five_even_txns"
          - "status-success=ci/circleci: test--test_postake_snarkless"
          - "status-success=ci/circleci: test--test_postake_split"
          - "status-success=ci/circleci: test--test_postake_split_snarkless"
          - "status-success=ci/circleci: test--test_postake_txns"
          - "status-success=ci/circleci: test-unit--dev"
          - "status-success=ci/circleci: test-unit--nonconsensus_medium_curves"
          - "status-success=ci/circleci: tracetool"
          - "#approved-reviews-by>=1"
          - label=ready-to-merge
      actions:
          merge:
              method: squash
              strict: smart
          delete_head_branch: {}