[build]
  command = "yarn export"
  base = "frontend/website"
  publish = "out"
  ignore = "git diff --quiet HEAD^ HEAD -- . || git diff --quiet origin/develop HEAD -- ."

[context.deploy-preview]
  command = "yarn export && echo 'User-agent: *\nDisallow: /' > out/robots.txt"

[context.branch-deploy]
  command = "yarn export && echo 'User-agent: *\nDisallow: /' > out/robots.txt"
