---
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl $.Values.exporter.name . }}
spec:
  type: NodePort
  selector:
    app: {{ tpl $.Values.exporter.name . }}
  ports:
  - name: metric-collection
    protocol: TCP
    port: {{ $.Values.exporter.listeningPort }}
    targetPort: {{ $.Values.exporter.listeningPort }}
